apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: sample1
    tier: frontend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: sample1
    tier: frontend
